spring.application.name=Cinebokk

spring.datasource.url=jdbc:mysql://localhost:3306/Cinebok

spring.datasource.username=root

spring.datasource.password=Sakshik@173

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8080

razorpay.key=rzp_test_T4ByhGZwfMugDS

razorpay.secret=g3frlQ3r2t6cC52rQlq7SLe5


jwt.secret=MySecretKeyForCinebokkJwtToken2026VerySecureKey

jwt.expiration=86400000